### ISSUE TITLE
http server

### ISSUE THREAD

**Issue by AlexeyRoza** [dedok/nginx-tutorials#2]
здравствуйте
посмотрел доклад про модули для NGINX: https://www.youtube.com/watch?v=N_8Zk281vNE
такой вопрос: как лучше всего делать http-сервер на C/C++:
написать fcgi-демона
,ИЛИ NGINX-модуль
,ИЛИ там весь запрос разбирается разными модулями
,ИЛИ ещё как?
(модули на C++ можно писать? В докладе было упоминание C++...)

**Comment by dedok** [comment]
Привет,

Зависит от задач. Если хотите, то можем обсудить используя почту, мой адрес: dedok.mad@gmail.com.

Но если коротко и в целом. Если нужен просто HTTP сервер, который связывает условную СУБД и на котором крутиться бизнес логика, то я могу посоветовать реализовать его используя условный go, C/C++, что-то еще, а NGINX использовать как proxy (directive proxy_pass).

Также могу посоветовать посмотреть в сторону NGINX.Unit, он кажется неплох для таких задач.
